name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale as it is inactive for a longer period.'
        stale-pr-message: 'This pull request is marked as stale because of inactivity. Please contact the collaborators via mentioning to ensure that you are still working on this. \nSorry for any inconvenience caused!'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
